### ISSUE TITLE
I wish i could run it in java 1.8. 

### ISSUE THREAD

**Issue by hangum** [kornilova-l/mongo-jdbc-driver#2]
I wish I could run it in JAVA 1.8.

Man underlying libraries still work with Java 1.8.
I hope it is compatible with 1.8. 

Thanks.

**Comment by hangum** [comment]
@kornilova-l 
I'm making Eclipse RCP products. 
When I looked at stackoverflow, i found the following answers.
-Dorg.osgi.framework.bundle.parent=ext 

Thank you.

reference: 
https://stackoverflow.com/questions/36317684/eclipse-jsdt-internal-error-noclassdeffounderror-jdk-nashorn-internal-runtime
